'use client'

// deploy-trigger: 2026-09-21-git-reconnected

import Image from "next/image";
import Link from "next/link";
import { Suspense, useEffect, useMemo, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { Check, ChevronDown, Heart, Minus, PackageCheck, Plus, RotateCcw, ShieldCheck, Truck } from "lucide-react";

type Product={name:string;sku:string;brand:string;category:string;price:number;oldPrice:number;discount:number;stock:number;collection:string;state:string;imageUrl?:string;description?:string;color?:string;sizes?:string[]}
const KEY='rua-admin-products-v1';
const knownImages:Record<string,string>={
'RUA-0001':'/brand/vestido-lino-vera.png','RUA-0002':'/brand/camisa-serena.png','RUA-0003':'/brand/pantalon-amalfi.png','RUA-0004':'/brand/blazer-vera.png',
'RUA-0011':'/brand/bolso-ayra-weekend.png','RUA-0014':'/brand/vela-baltic-amber.png','RUA-0015':'/brand/difusor-french-cade.png','RUA-0022':'/brand/set-home-aroma.png',
'RUA-0025':'/brand/gift-box-rua.png','RUA-0026':'/brand/fragancia-rua-vera.png'};
const raw:any[][]=[
['Vestido Lino Vera','RUA-0001','Paradiso','Moda',590000,690000,14,12,'Nueva temporada'],['Camisa Serena','RUA-0002','Las Sureñas','Moda',420000,490000,14,18,'Nueva temporada'],['Pantalón Amalfi','RUA-0003','Lanhtropy','Moda',510000,590000,14,10,'Resort'],['Blazer Vera','RUA-0004','ERNESTINA','Moda',780000,890000,12,7,'RUA Edit'],['Top Aura','RUA-0005','MAZ by RUA','Moda',290000,340000,15,22,'RUA Edit'],['Falda Midi Clara','RUA-0006','Bahía María','Moda',450000,520000,13,14,'Resort'],['Vestido Noche Sur','RUA-0007','Heidi Clair','Moda',890000,990000,10,6,'Noche'],['Sandalia Alma','RUA-0008','Flabelus','Moda',650000,720000,10,9,'Resort'],['Kimono Ati','RUA-0009','AT – Ati Troche','Moda',540000,620000,13,11,'RUA Edit'],['Cartera Angelo Mini','RUA-0010','ANGELO','Objetos & Diseño',720000,820000,12,8,'Piezas con identidad'],['Bolso Ayra Weekend','RUA-0011','AYRA','Objetos & Diseño',680000,760000,11,5,'Piezas con identidad'],['Sombrero Fedora Classic','RUA-0012','FEDORA','Moda',390000,450000,13,13,'Accesorios'],['Libro Fashion Icons','RUA-0013','TASCHEN','Objetos & Diseño',480000,480000,0,9,'Books'],['Vela Baltic Amber','RUA-0014','VOLUSPA','Lifestyle',360000,420000,14,16,'Aromas'],['Difusor French Cade','RUA-0015','VOLUSPA','Lifestyle',410000,470000,13,12,'Aromas'],['Cuaderno Papelê RUA','RUA-0016','PAPELÊ','Objetos & Diseño',145000,170000,15,25,'Papelería'],['Agenda Papelê 2027','RUA-0017','PAPELÊ','Objetos & Diseño',195000,230000,15,20,'Papelería'],['Collar Angelo Line','RUA-0018','ANGELO','Moda',330000,390000,15,15,'Accesorios'],['Pañuelo Bahía','RUA-0019','Bahía María','Moda',220000,260000,15,17,'Accesorios'],['Camisa Resort','RUA-0020','Lanhtropy','Moda',470000,540000,13,9,'Resort'],['Vestido Paradiso Sol','RUA-0021','Paradiso','Moda',640000,740000,14,8,'Resort'],['Set Home Aroma','RUA-0022','VOLUSPA','Lifestyle',590000,680000,13,7,'Aromas'],['Bandeja Ayra Deco','RUA-0023','AYRA','Objetos & Diseño',280000,330000,15,10,'Home'],['Libro Interior Design','RUA-0024','TASCHEN','Objetos & Diseño',520000,520000,0,6,'Books'],['Gift Box RUA','RUA-0025','RUA Vera','Lifestyle',450000,520000,13,20,'RUA Edit'],
['Fragancia RUA','RUA-0026','RUA Vera','Aromas & Fragancias',0,0,0,1,'Fragancias'],['Objeto Aromático RUA','RUA-0027','RUA Vera','Aromas & Fragancias',0,0,0,1,'Aromas'],['Set de Sellos Papelê','RUA-0028','PAPELÊ','Papelería & Diseño',0,0,0,1,'Papelería'],['Anteojos de Sol Ámbar','RUA-0029','RUA Vera','Accesorios',0,0,0,1,'Eyewear'],['Anteojos de Sol Havana','RUA-0030','RUA Vera','Accesorios',0,0,0,1,'Eyewear'],['Anteojos de Sol Classic','RUA-0031','RUA Vera','Accesorios',0,0,0,1,'Eyewear']];
const fallback:Product[]=raw.map(x=>({name:x[0],sku:x[1],brand:x[2],category:x[3],price:x[4],oldPrice:x[5],discount:x[6],stock:x[7],collection:x[8],state:'Activo',imageUrl:knownImages[x[1]],color:'Crudo',sizes:x[3]==='Moda'?['S','M','L','XL']:[],description:`${x[0]} de ${x[2]}, seleccionado por RUA Vera por su identidad, diseño y calidad.`}));
function money(n:number){return n>0?`Gs. ${new Intl.NumberFormat('es-PY').format(n)}`:'Consultar precio'}
function enrich(p:Product):Product{return {...p,imageUrl:p.imageUrl||knownImages[p.sku],color:p.color||'Crudo',sizes:p.sizes??(p.category==='Moda'?['S','M','L','XL']:[]),description:p.description||`${p.name} de ${p.brand}, seleccionado por RUA Vera por su identidad, diseño y calidad.`}}

function DemoProductContent(){
 const router=useRouter(),params=useSearchParams(),sku=params.get('sku')||'RUA-0001';
 const [products,setProducts]=useState<Product[]>(fallback),[selectedSize,setSelectedSize]=useState<string|null>(null),[quantity,setQuantity]=useState(1),[error,setError]=useState(false),[open,setOpen]=useState<string|null>('details');
 useEffect(()=>{try{const saved=localStorage.getItem(KEY);if(saved){const parsed=JSON.parse(saved) as Product[];if(Array.isArray(parsed)&&parsed.length){const map=new Map(fallback.map(p=>[p.sku,p]));parsed.forEach(p=>map.set(p.sku,enrich(p)));setProducts(Array.from(map.values()))}}}catch{}},[]);
 useEffect(()=>{setSelectedSize(null);setQuantity(1);setError(false)},[sku]);
 const product=useMemo(()=>enrich(products.find(p=>p.sku===sku&&String(p.state).toLowerCase()==='activo')||fallback.find(p=>p.sku===sku)||fallback[0]),[products,sku]);
 const related=useMemo(()=>products.filter(p=>p.sku!==product.sku&&p.category===product.category&&String(p.state).toLowerCase()==='activo').slice(0,4).map(enrich),[products,product]);
 const needsSize=(product.sizes?.length||0)>0;
 const add=()=>{if(needsSize&&!selectedSize){setError(true);return}setError(false);sessionStorage.setItem('rua-demo-product',JSON.stringify({name:product.name,sku:product.sku,price:product.price,size:selectedSize,color:product.color,quantity,image:product.imageUrl}));router.push(`/demo-checkout?sku=${encodeURIComponent(product.sku)}&size=${encodeURIComponent(selectedSize||'')}&color=${encodeURIComponent(product.color||'')}&quantity=${quantity}`)};
 const accordion=(id:string,title:string,body:React.ReactNode)=><div className="border-t border-[#d9d2cb]"><button type="button" onClick={()=>setOpen(open===id?null:id)} className="flex w-full items-center justify-between py-5 text-left text-[10px] uppercase tracking-[0.18em]"><span>{title}</span><ChevronDown size={14} className={`transition ${open===id?'rotate-180':''}`}/></button>{open===id&&<div className="pb-6 text-sm leading-7 text-[#6e6965]">{body}</div>}</div>;
 return <main className="min-h-screen bg-[#f7f4ef] text-[#201e1c]">
 <div className="mx-auto flex w-[94%] max-w-[1500px] items-center gap-2 py-6 text-[9px] uppercase tracking-[0.16em] text-[#6e6965]"><Link href="/">Inicio</Link><span>/</span><Link href={`/shop?category=${encodeURIComponent(product.category)}`}>{product.category}</Link><span>/</span><span className="text-[#201e1c]">{product.name}</span></div>
 <section className="mx-auto grid w-[94%] max-w-[1500px] gap-10 pb-16 lg:grid-cols-[1.08fr_.92fr] lg:gap-16"><div><div className="relative aspect-[4/5] max-h-[760px] overflow-hidden bg-[#e9e1d8]">{product.imageUrl?<Image src={product.imageUrl} alt={`${product.name} de ${product.brand}`} fill priority className="object-cover" sizes="(max-width:1024px) 100vw,55vw"/>:<span className="absolute inset-0 flex items-center justify-center font-serif text-8xl text-[#201e1c]/10">RUA</span>}{product.discount>0&&<span className="absolute left-5 top-5 bg-[#201e1c] px-3 py-2 text-[9px] tracking-[.16em] text-white">-{product.discount}%</span>}</div></div>
 <aside className="self-start lg:sticky lg:top-28"><div className="flex items-start justify-between gap-5"><div><p className="text-[10px] font-semibold uppercase tracking-[.2em]">{product.brand}</p><h1 className="mt-3 font-serif text-4xl lg:text-5xl">{product.name}</h1><p className="mt-3 text-[10px] uppercase tracking-[.15em] text-[#77716c]">{product.collection} · {product.sku}</p></div><button aria-label="Agregar a favoritos" className="border border-[#d9d2cb] p-3"><Heart size={18}/></button></div>
 <div className="mt-6 flex items-center gap-3"><p className="text-lg">{money(product.price)}</p>{product.oldPrice>product.price&&product.price>0&&<p className="text-sm text-[#8f8a87] line-through">{money(product.oldPrice)}</p>}{product.discount>0&&<span className="bg-[#201e1c] px-2.5 py-1.5 text-[9px] text-white">-{product.discount}%</span>}</div><p className="mt-6 max-w-lg text-sm leading-7 text-[#6e6965]">{product.description}</p>
 {needsSize&&<div className="mt-8 border-t border-[#d9d2cb] pt-6"><p className="text-[10px] uppercase tracking-[.18em]">Talle</p><div className="mt-4 grid grid-cols-4 gap-2">{product.sizes!.map(size=><button type="button" key={size} onClick={()=>{setSelectedSize(size);setError(false)}} className={`relative border py-3.5 text-xs ${selectedSize===size?'border-[#201e1c] bg-[#201e1c] text-white':'border-[#d9d2cb] bg-white'}`}>{size}{selectedSize===size&&<Check size={12} className="absolute right-2 top-2"/>}</button>)}</div>{error&&<p className="mt-3 text-xs text-[#8a332b]">Seleccioná un talle para continuar.</p>}</div>}
 <div className="mt-6 grid grid-cols-[1fr_auto] items-end gap-6"><div><p className="text-[10px] uppercase tracking-[.18em]">Color</p><div className="mt-3 inline-flex items-center gap-2 border border-[#201e1c] bg-white px-4 py-3 text-xs">{product.color}<Check size={12}/></div></div><div><p className="text-[10px] uppercase tracking-[.18em]">Cantidad</p><div className="mt-3 flex h-[42px] items-center border bg-white"><button onClick={()=>setQuantity(q=>Math.max(1,q-1))} className="w-10"><Minus size={13} className="mx-auto"/></button><span className="min-w-8 text-center text-xs">{quantity}</span><button onClick={()=>setQuantity(q=>Math.min(product.stock||1,q+1))} className="w-10"><Plus size={13} className="mx-auto"/></button></div></div></div>
 <button type="button" onClick={add} disabled={product.stock<=0} className="mt-8 block w-full bg-[#201e1c] py-5 text-[10px] uppercase tracking-[.2em] text-white disabled:opacity-40">{product.stock>0?'Agregar al carrito':'Producto agotado'}</button><p className="mt-3 text-center text-[9px] uppercase tracking-[.14em] text-[#77716c]">{product.stock} unidades disponibles · Compra segura</p>
 <div className="mt-8 grid grid-cols-3 border-y border-[#d9d2cb] py-5"><div className="text-center"><Truck size={18} className="mx-auto"/><p className="mt-2 text-[8px] uppercase">Envíos</p></div><div className="text-center"><PackageCheck size={18} className="mx-auto"/><p className="mt-2 text-[8px] uppercase">Retiro en RUA</p></div><div className="text-center"><ShieldCheck size={18} className="mx-auto"/><p className="mt-2 text-[8px] uppercase">Compra segura</p></div></div>
 <div className="mt-4">{accordion('details','Detalles del producto',<p>{product.description}</p>)}{accordion('shipping','Envíos y retiros',<p>Podés seleccionar envío o retiro durante el proceso de compra.</p>)}{accordion('changes','Cambios',<p>Los cambios están sujetos a disponibilidad y condiciones comerciales vigentes.</p>)}</div></aside></section>
 <section className="mx-auto max-w-[1500px] px-[4%] py-16"><div className="mb-8 flex justify-between border-b pb-5"><div><p className="text-[9px] uppercase tracking-[.2em] text-[#77716c]">También te puede gustar</p><h2 className="mt-2 font-serif text-4xl">Más de {product.category}</h2></div><Link href={`/shop?category=${encodeURIComponent(product.category)}`} className="text-[9px] uppercase">Ver categoría →</Link></div><div className="grid grid-cols-2 gap-3 md:grid-cols-4">{related.map((p,i)=><Link key={p.sku} href={`/demo-product?sku=${encodeURIComponent(p.sku)}`} className="group"><div className="relative aspect-[3/4] overflow-hidden bg-[#ddd4cb]">{p.imageUrl?<Image src={p.imageUrl} alt={p.name} fill className="object-cover"/>:<span className="absolute inset-0 flex items-center justify-center font-serif text-5xl text-black/10">RUA</span>}</div><p className="mt-3 text-[9px] font-semibold uppercase">{p.brand}</p><h3 className="mt-1 font-serif text-lg">{p.name}</h3><p className="text-xs">{money(p.price)}</p></Link>)}</div></section>
 <section className="bg-[#201e1c] px-[5%] py-14 text-center text-white"><RotateCcw size={20} className="mx-auto text-white/60"/><p className="mt-4 text-[9px] uppercase tracking-[.22em] text-white/55">RUA Vera · Marcas con identidad</p><h2 className="mx-auto mt-4 max-w-2xl font-serif text-3xl">Descubrí piezas seleccionadas con identidad.</h2></section></main>
}


export default function DemoProductPage(){
 return <Suspense fallback={<main className="min-h-screen bg-[#f7f4ef]" />}><DemoProductContent /></Suspense>
}
