"use client";
import { useMemo, useState } from "react";
import { FolderTree, Plus, X } from "lucide-react";

const demoProducts=[
["Vestido Lino Vera","Moda"],["Camisa Serena","Moda"],["Pantalón Amalfi","Moda"],["Blazer Vera","Moda"],["Top Aura","Moda"],["Falda Midi Clara","Moda"],["Vestido Noche Sur","Moda"],["Sandalia Alma","Moda"],["Kimono Atí","Moda"],["Sombrero Fedora Classic","Moda"],["Collar Angelo Line","Moda"],["Pañuelo Bahía","Moda"],["Camisa Resort","Moda"],["Vestido Paradiso Sol","Moda"],
["Vela Baltic Amber","Lifestyle"],["Difusor French Cade","Lifestyle"],["Set Home Aroma","Lifestyle"],["Gift Box RUA","Lifestyle"],
["Cartera Angelo Mini","Objetos & Diseño"],["Bolso Ayra Weekend","Objetos & Diseño"],["Libro Fashion Icons","Objetos & Diseño"],["Cuaderno Papelê RUA","Objetos & Diseño"],["Agenda Papelê 2027","Objetos & Diseño"],["Bandeja Ayra Deco","Objetos & Diseño"],["Libro Interior Design","Objetos & Diseño"]
] as const;

const initial=[
{name:"Moda",slug:"moda",description:"Prendas, accesorios y propuestas de moda seleccionadas por RUA.",active:true,home:true},
{name:"Lifestyle",slug:"lifestyle",description:"Aromas, sets y piezas para vivir el universo RUA más allá de la moda.",active:true,home:true},
{name:"Objetos & Diseño",slug:"objetos-diseno",description:"Objetos, libros y piezas de diseño con identidad.",active:true,home:true},
];

export default function CategoriesPage(){
 const[open,setOpen]=useState(false); const[selected,setSelected]=useState<string|null>(null);
 const categories=useMemo(()=>initial.map(c=>({...c,products:demoProducts.filter(p=>p[1]===c.name)})),[]);
 return <div className="mx-auto max-w-[1500px]">
  <div className="flex items-end justify-between border-b border-[#d6cfc8] pb-6"><div><p className="text-[10px] uppercase tracking-[.2em] text-[#817a74]">Organización del catálogo</p><h1 className="mt-2 font-serif text-4xl">Categorías</h1><p className="mt-2 text-sm text-[#756f69]">Los 25 productos demo ya están separados por categoría. Desde acá podés controlar cómo se organiza la tienda.</p></div><button onClick={()=>setOpen(true)} className="hidden items-center gap-2 bg-[#201e1c] px-5 py-3 text-[10px] uppercase tracking-[.16em] text-white sm:flex"><Plus className="size-4"/> Nueva categoría</button></div>
  <div className="mt-6 grid gap-4 md:grid-cols-3">{categories.map((x,i)=><div key={x.name} className="border border-[#d9d2cb] bg-[#fbf9f6] p-5"><div className="flex justify-between"><span className="text-[9px] uppercase tracking-[.18em] text-[#817a74]">0{i+1}</span><span className="text-[9px] uppercase tracking-[.14em] text-emerald-700">Visible</span></div><div className="mt-8 flex size-10 items-center justify-center bg-[#ebe5df]"><FolderTree className="size-4"/></div><h2 className="mt-5 font-serif text-2xl">{x.name}</h2><p className="mt-2 min-h-10 text-xs leading-5 text-[#817a74]">{x.description}</p><div className="mt-5 flex items-end justify-between border-t border-[#ddd6cf] pt-4"><div><p className="font-serif text-3xl">{x.products.length}</p><p className="text-[9px] uppercase tracking-[.14em] text-[#817a74]">productos relacionados</p></div><button onClick={()=>setSelected(selected===x.name?null:x.name)} className="border-b border-[#201e1c] pb-1 text-[9px] uppercase tracking-[.14em]">{selected===x.name?"Ocultar":"Ver productos"}</button></div>{selected===x.name&&<div className="mt-5 border-t border-[#ddd6cf] pt-4"><p className="mb-3 text-[9px] uppercase tracking-[.16em] text-[#817a74]">Productos de {x.name}</p><div className="space-y-2">{x.products.map(([name])=><div key={name} className="flex items-center justify-between bg-[#f1ece6] px-3 py-2 text-xs"><span>{name}</span><span className="text-[9px] uppercase text-emerald-700">Activo</span></div>)}</div></div>}<div className="mt-6 flex gap-4 text-[9px] uppercase tracking-[.14em]"><button onClick={()=>setOpen(true)}>Editar</button><button onClick={()=>setSelected(x.name)}>Relacionar productos</button></div></div>)}</div>
  <div className="mt-6 border border-[#d9d2cb] bg-[#eee9e3] p-5"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-[10px] uppercase tracking-[.16em] text-[#817a74]">Resumen</p><p className="mt-1 font-serif text-2xl">3 categorías · 25 productos relacionados</p></div><p className="text-xs text-[#756f69]">Moda: 14 · Lifestyle: 4 · Objetos & Diseño: 7</p></div></div>
  <button onClick={()=>setOpen(true)} className="mt-5 flex items-center gap-2 bg-[#201e1c] px-5 py-3 text-[10px] uppercase tracking-[.16em] text-white sm:hidden"><Plus className="size-4"/> Nueva categoría</button>
  {open&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/35 p-4"><form onSubmit={e=>{e.preventDefault();setOpen(false)}} className="w-full max-w-lg bg-[#f7f4ef] p-6 shadow-2xl"><div className="flex justify-between"><h2 className="font-serif text-3xl">Categoría</h2><button type="button" onClick={()=>setOpen(false)}><X/></button></div><div className="mt-7 space-y-4"><Input label="Nombre" placeholder="Ej. Accesorios"/><Input label="Slug" placeholder="accesorios"/><Input label="Descripción" placeholder="Descripción de la categoría"/><label className="flex items-center gap-3 text-sm"><input type="checkbox" defaultChecked/> Visible en la tienda</label><label className="flex items-center gap-3 text-sm"><input type="checkbox"/> Destacar en Home</label></div><button className="mt-7 w-full bg-[#201e1c] py-3 text-xs text-white">Guardar categoría</button></form></div>}
 </div>
}
function Input({label,placeholder}:{label:string;placeholder:string}){return <label className="block"><span className="text-[10px] uppercase tracking-[.14em] text-[#706a65]">{label}</span><input placeholder={placeholder} className="mt-2 h-11 w-full border border-[#d8d1ca] bg-white px-3 text-sm outline-none"/></label>}
