'use client'
import { useState } from 'react'
import Link from 'next/link'
import { Check, CreditCard, MapPin, Store } from 'lucide-react'

const money=(v:number)=>`Gs. ${new Intl.NumberFormat('es-PY').format(v)}`
type Delivery='delivery'|'pickup'; type Pay='card'|'transfer'|'store'

export default function DemoCheckout(){
 const [step,setStep]=useState(1); const [delivery,setDelivery]=useState<Delivery>('delivery'); const [pay,setPay]=useState<Pay>('card'); const [done,setDone]=useState(false); const [form,setForm]=useState({name:'',phone:'',email:'',document:'',ruc:'',invoice:'',city:'',neighborhood:'',address:'',reference:''}); const change=(e:React.ChangeEvent<HTMLInputElement>)=>setForm({...form,[e.target.name]:e.target.value}); const valid=form.name&&form.phone&&form.email&&(delivery==='pickup'||(form.city&&form.address)); const field='w-full border border-[#d9d2cb] bg-white px-4 py-4 text-sm outline-none focus:border-[#201e1c]'
 if(done)return <main className="flex min-h-[75vh] items-center justify-center bg-[#f7f4ef] px-6 text-[#201e1c]"><div className="max-w-xl text-center"><div className="mx-auto flex h-14 w-14 items-center justify-center rounded-full bg-[#201e1c] text-white"><Check/></div><p className="mt-7 text-[9px] uppercase tracking-[0.2em]">Prueba completada</p><h1 className="mt-3 font-serif text-5xl">El recorrido funciona.</h1><p className="mt-5 text-sm leading-7 text-[#6e6965]">Pedido demo RUA-0001 creado únicamente en pantalla. No se guardó una venta real y no se realizó ningún cobro.</p><div className="mt-8 border-y border-[#d9d2cb] py-5 text-sm"><p>Vestido RUA Demo · Talle M · Negro</p><p className="mt-2">{delivery==='pickup'?'Retiro en tienda':'Entrega a domicilio'} · {pay==='card'?'Tarjeta':pay==='transfer'?'Transferencia':'Pago coordinado'}</p><strong className="mt-3 block">{money(590000)}</strong></div><Link href="/demo-product" className="mt-8 inline-block bg-[#201e1c] px-8 py-4 text-[10px] uppercase tracking-[0.18em] text-white">Probar nuevamente</Link></div></main>
 return <main className="min-h-screen bg-[#f7f4ef] px-[4%] py-12 text-[#201e1c]"><div className="mx-auto max-w-[1250px]"><div className="mb-10 flex items-end justify-between"><div><p className="text-[9px] uppercase tracking-[0.2em]">Demo de compra · Paso {step} de 3</p><h1 className="mt-2 font-serif text-5xl">{step===1?'Tu carrito':step===2?'Entrega y facturación':'Forma de pago'}</h1></div><Link href="/demo-product" className="text-[9px] uppercase tracking-[0.15em] underline">Volver al producto</Link></div><div className="grid gap-12 lg:grid-cols-[1fr_360px]"><section>
 {step===1&&<div><div className="grid grid-cols-[100px_1fr] gap-5 border-y border-[#d9d2cb] py-6"><div className="flex aspect-[3/4] items-center justify-center bg-[#d9d1c9] font-serif text-2xl text-[#aaa19a]">RUA</div><div><p className="text-[9px] uppercase tracking-[0.18em]">RUA Vera</p><h2 className="mt-2 font-serif text-2xl">Vestido RUA Demo</h2><p className="mt-2 text-xs text-[#6e6965]">Talle M · Negro · Cantidad 1</p><p className="mt-4">{money(590000)}</p></div></div><button onClick={()=>setStep(2)} className="mt-8 w-full bg-[#201e1c] py-5 text-[10px] uppercase tracking-[0.18em] text-white">Continuar compra</button></div>}
 {step===2&&<div className="space-y-9"><div><h2 className="font-serif text-2xl">¿Cómo querés recibir tu compra?</h2><div className="mt-4 grid gap-3 sm:grid-cols-2"><button onClick={()=>setDelivery('delivery')} className={`border p-5 text-left ${delivery==='delivery'?'border-[#201e1c] bg-white':'border-[#d9d2cb]'}`}><MapPin/><b className="mt-3 block">Entrega a domicilio</b></button><button onClick={()=>setDelivery('pickup')} className={`border p-5 text-left ${delivery==='pickup'?'border-[#201e1c] bg-white':'border-[#d9d2cb]'}`}><Store/><b className="mt-3 block">Retiro en tienda</b></button></div></div><div><h2 className="font-serif text-2xl">Contacto</h2><div className="mt-4 grid gap-3 sm:grid-cols-2"><input name="name" onChange={change} placeholder="Nombre y apellido *" className={field}/><input name="phone" onChange={change} placeholder="Celular / WhatsApp *" className={field}/><input name="email" onChange={change} placeholder="Correo electrónico *" className={`${field} sm:col-span-2`}/></div></div><div><h2 className="font-serif text-2xl">Facturación</h2><div className="mt-4 grid gap-3 sm:grid-cols-2"><input name="document" onChange={change} placeholder="Cédula" className={field}/><input name="ruc" onChange={change} placeholder="RUC" className={field}/><input name="invoice" onChange={change} placeholder="Nombre / Razón social" className={`${field} sm:col-span-2`}/></div></div>{delivery==='delivery'&&<div><h2 className="font-serif text-2xl">Dirección de entrega</h2><div className="mt-4 grid gap-3 sm:grid-cols-2"><input name="city" onChange={change} placeholder="Ciudad *" className={field}/><input name="neighborhood" onChange={change} placeholder="Barrio" className={field}/><input name="address" onChange={change} placeholder="Calle, número, casa/edificio *" className={`${field} sm:col-span-2`}/><input name="reference" onChange={change} placeholder="Referencia del lugar" className={`${field} sm:col-span-2`}/></div></div>}<button disabled={!valid} onClick={()=>setStep(3)} className="w-full bg-[#201e1c] py-5 text-[10px] uppercase tracking-[0.18em] text-white disabled:opacity-30">Continuar a formas de pago</button></div>}
 {step===3&&<div><h2 className="font-serif text-2xl">Elegí cómo pagar</h2><div className="mt-5 space-y-3">{[['card','Tarjeta de crédito o débito'],['transfer','Transferencia bancaria'],['store','Pago coordinado con la tienda']].map(([id,title])=><button key={id} onClick={()=>setPay(id as Pay)} className={`flex w-full items-center gap-4 border p-5 text-left ${pay===id?'border-[#201e1c] bg-white':'border-[#d9d2cb]'}`}><CreditCard size={18}/><span className="flex-1">{title}</span>{pay===id&&<Check size={16}/>}</button>)}</div><p className="mt-5 text-xs leading-6 text-[#6e6965]">Modo demo: ninguna opción realizará un cobro real.</p><div className="mt-8 grid grid-cols-2 gap-3"><button onClick={()=>setStep(2)} className="border border-[#201e1c] py-4 text-[10px] uppercase tracking-[0.16em]">Volver</button><button onClick={()=>setDone(true)} className="bg-[#201e1c] py-4 text-[10px] uppercase tracking-[0.16em] text-white">Confirmar pedido demo</button></div></div>}
 </section><aside className="h-fit border border-[#d9d2cb] bg-white p-6 lg:sticky lg:top-36"><p className="text-[9px] uppercase tracking-[0.18em] text-[#6e6965]">Resumen demo</p><h3 className="mt-4 font-serif text-xl">Vestido RUA Demo</h3><p className="mt-1 text-xs text-[#6e6965]">Talle M · Negro · 1 unidad</p><div className="mt-6 flex justify-between border-t border-[#d9d2cb] pt-5"><span>Total</span><strong>{money(590000)}</strong></div><p className="mt-5 text-xs leading-6 text-[#6e6965]">No crea una venta real, no descuenta stock y no cobra dinero.</p></aside></div></div></main>
}
