"use client";

import { useMemo, useRef, useState } from "react";
import { AlertCircle, CheckCircle2, Download, FileSpreadsheet, ImagePlus, Plus, Search, Upload, X } from "lucide-react";

type ImportRow = { name:string; sku:string; brand:string; category:string; price:string; oldPrice:string; discount:string; stock:string; status:string };

const demoRows: ImportRow[] = [
  {name:"Vestido lino",sku:"RUA-0001",brand:"Paradiso",category:"Moda",price:"590000",oldPrice:"690000",discount:"14",stock:"12",status:"Listo"},
  {name:"Vela Voluspa",sku:"RUA-0002",brand:"Voluspa",category:"Lifestyle",price:"320000",oldPrice:"",discount:"0",stock:"8",status:"Listo"},
  {name:"Bolso Fedora",sku:"RUA-0003",brand:"Fedora",category:"Objetos & Diseño",price:"480000",oldPrice:"",discount:"0",stock:"0",status:"Revisar stock"},
];

export default function ProductsPage() {
  const [open,setOpen]=useState(false);
  const [bulk,setBulk]=useState(false);
  const [search,setSearch]=useState("");
  const [fileName,setFileName]=useState("");
  const [rows,setRows]=useState<ImportRow[]>([]);
  const [imported,setImported]=useState(false);
  const fileRef=useRef<HTMLInputElement>(null);
  const ready=useMemo(()=>rows.filter(r=>r.status==="Listo").length,[rows]);

  const loadFile=(file?:File)=>{if(!file)return;setFileName(file.name);setRows(demoRows);setImported(false)};
  const downloadTemplate=()=>{
    const csv="nombre,sku,marca,categoria,precio,precio_anterior,descuento_porcentaje,stock,talles,colores,coleccion,estado,descripcion,url_imagen\nVestido lino,RUA-0001,Paradiso,Moda,590000,690000,14,12,\"S,M,L,XL\",\"Negro,Crudo\",Nueva temporada,Activo,Descripcion comercial,https://...";
    const blob=new Blob([csv],{type:"text/csv;charset=utf-8"}); const url=URL.createObjectURL(blob); const a=document.createElement("a");a.href=url;a.download="plantilla-productos-rua.csv";a.click();URL.revokeObjectURL(url);
  };

  return <div className="mx-auto max-w-[1500px]">
    <div className="flex flex-col gap-4 border-b border-[#d6cfc8] pb-6 md:flex-row md:items-end md:justify-between"><div><p className="text-[10px] uppercase tracking-[.2em] text-[#817a74]">Catálogo</p><h1 className="mt-2 font-serif text-4xl">Productos</h1><p className="mt-2 text-sm text-[#756f69]">Administrá productos individualmente o cargá cientos de una sola vez con Excel.</p></div><div className="flex flex-wrap gap-2"><button onClick={()=>setBulk(true)} className="flex items-center gap-2 border border-[#201e1c] bg-white px-5 py-3 text-[10px] uppercase tracking-[.16em]"><FileSpreadsheet className="size-4"/> Importar Excel</button><button onClick={()=>setOpen(true)} className="flex items-center gap-2 bg-[#201e1c] px-5 py-3 text-[10px] uppercase tracking-[.16em] text-white"><Plus className="size-4"/> Nuevo producto</button></div></div>

    <div className="mt-6 grid gap-3 sm:grid-cols-3"><Stat value="0" label="Productos"/><Stat value="0" label="Stock total"/><Stat value="0" label="Con descuento"/></div>
    <div className="mt-5 border border-[#d9d2cb] bg-[#fbf9f6]"><div className="flex flex-col gap-3 border-b border-[#ddd6cf] p-4 md:flex-row"><label className="flex flex-1 items-center gap-3 border border-[#ddd6cf] bg-white px-4"><Search className="size-4 text-[#817a74]"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar por nombre, SKU o marca" className="h-11 w-full bg-transparent text-sm outline-none"/></label><select className="h-11 border border-[#ddd6cf] bg-white px-4 text-sm"><option>Todas las categorías</option><option>Moda</option><option>Lifestyle</option><option>Objetos & Diseño</option></select><select className="h-11 border border-[#ddd6cf] bg-white px-4 text-sm"><option>Todos los estados</option><option>Activo</option><option>Borrador</option><option>Sin stock</option></select></div><div className="p-10 text-center"><PackageEmpty/><h2 className="mt-5 font-serif text-2xl">Tu catálogo empieza acá.</h2><p className="mx-auto mt-2 max-w-lg text-sm leading-6 text-[#817a74]">Podés crear un producto manualmente o importar el catálogo completo desde una planilla.</p><button onClick={()=>setBulk(true)} className="mt-6 border-b border-[#201e1c] pb-1 text-[10px] uppercase tracking-[.16em]">Cargar productos masivamente →</button></div></div>

    {bulk&&<div className="fixed inset-0 z-50 overflow-y-auto bg-[#201e1c]/55 p-3 md:p-8"><div className="mx-auto max-w-6xl bg-[#f7f4ef] shadow-2xl"><div className="flex items-center justify-between border-b border-[#d9d2cb] px-5 py-5 md:px-7"><div><p className="text-[9px] uppercase tracking-[.2em] text-[#817a74]">Importación masiva</p><h2 className="font-serif text-3xl">Cargar productos desde Excel</h2></div><button onClick={()=>setBulk(false)}><X/></button></div>
      <div className="p-5 md:p-7"><div className="grid gap-4 lg:grid-cols-3"><Step n="01" title="Descargá la plantilla" copy="Usá las columnas preparadas para RUA: producto, SKU, marca, categoría, precio, descuento, stock, variantes e imágenes."><button onClick={downloadTemplate} className="mt-5 flex items-center gap-2 border-b border-[#201e1c] pb-1 text-[10px] uppercase tracking-[.15em]"><Download className="size-4"/> Descargar plantilla</button></Step><Step n="02" title="Completá tu catálogo" copy="Una fila por producto. Las categorías, marcas, precios y descuentos se procesan juntos."/><Step n="03" title="Subí y revisá" copy="Antes de publicar, el panel muestra errores y una vista previa para evitar cargas incorrectas."/></div>
      <div onClick={()=>fileRef.current?.click()} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();loadFile(e.dataTransfer.files[0])}} className="mt-6 flex min-h-52 cursor-pointer flex-col items-center justify-center border border-dashed border-[#9f9891] bg-white p-8 text-center"><Upload className="size-7"/><p className="mt-4 font-serif text-2xl">Arrastrá tu Excel acá</p><p className="mt-2 text-sm text-[#817a74]">o hacé clic para seleccionar .xlsx, .xls o .csv</p><input ref={fileRef} type="file" accept=".xlsx,.xls,.csv" className="hidden" onChange={e=>loadFile(e.target.files?.[0])}/>{fileName&&<span className="mt-4 bg-[#eee9e3] px-4 py-2 text-xs">{fileName}</span>}</div>
      {rows.length>0&&<div className="mt-6"><div className="mb-3 flex flex-wrap items-center justify-between gap-3"><div><h3 className="font-serif text-2xl">Vista previa</h3><p className="text-xs text-[#817a74]">{rows.length} filas detectadas · {ready} listas para importar</p></div><div className="flex gap-2 text-xs"><span className="flex items-center gap-1 bg-[#e8efe7] px-3 py-2"><CheckCircle2 className="size-4"/> {ready} correctas</span><span className="flex items-center gap-1 bg-[#f3e9df] px-3 py-2"><AlertCircle className="size-4"/> {rows.length-ready} revisar</span></div></div><div className="overflow-x-auto border border-[#d9d2cb] bg-white"><table className="w-full min-w-[900px] text-left text-xs"><thead className="bg-[#eee9e3] text-[9px] uppercase tracking-[.12em]"><tr>{["Producto","SKU","Marca","Categoría","Precio","Desc.","Stock","Estado"].map(x=><th key={x} className="px-4 py-3">{x}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={r.sku} className="border-t border-[#e5dfd9]"><td className="px-4 py-3 font-medium">{r.name}</td><td className="px-4 py-3">{r.sku}</td><td className="px-4 py-3">{r.brand}</td><td className="px-4 py-3">{r.category}</td><td className="px-4 py-3">Gs. {Number(r.price).toLocaleString("es-PY")}</td><td className="px-4 py-3">{r.discount}%</td><td className="px-4 py-3">{r.stock}</td><td className="px-4 py-3"><span className={r.status==="Listo"?"text-green-700":"text-amber-700"}>{r.status}</span></td></tr>)}</tbody></table></div><div className="mt-5 flex flex-col-reverse gap-3 sm:flex-row sm:justify-end"><button onClick={()=>{setRows([]);setFileName("")}} className="border border-[#cfc7c0] px-5 py-3 text-xs">Cambiar archivo</button><button onClick={()=>setImported(true)} disabled={ready===0} className="bg-[#201e1c] px-7 py-3 text-xs text-white disabled:opacity-40">Importar {ready} productos</button></div>{imported&&<div className="mt-4 flex items-start gap-3 border border-[#b9c9b7] bg-[#edf3ec] p-4 text-sm"><CheckCircle2 className="mt-0.5 size-5"/><div><b>Archivo validado.</b><p className="mt-1 text-xs text-[#5f695d]">La interfaz de importación está preparada. La persistencia definitiva se activará al conectar el catálogo con la base de datos.</p></div></div>}</div>}
      </div></div></div>}

    {open&&<div className="fixed inset-0 z-50 flex justify-end bg-black/35"><div className="h-full w-full max-w-2xl overflow-y-auto bg-[#f7f4ef] shadow-2xl"><div className="sticky top-0 z-10 flex items-center justify-between border-b border-[#d9d2cb] bg-[#f7f4ef] px-6 py-5"><div><p className="text-[9px] uppercase tracking-[.2em] text-[#817a74]">Catálogo RUA</p><h2 className="font-serif text-3xl">Nuevo producto</h2></div><button onClick={()=>setOpen(false)}><X/></button></div><form className="space-y-7 p-6" onSubmit={e=>{e.preventDefault();setOpen(false)}}><Field title="Información"><div className="grid gap-4 md:grid-cols-2"><Input label="Nombre del producto" placeholder="Ej. Vestido lino"/><Input label="Marca" placeholder="Ej. Paradiso"/><Input label="SKU" placeholder="RUA-0001"/><Select label="Estado" options={["Activo","Borrador"]}/></div><label className="block"><Span>Descripción</Span><textarea className="mt-2 min-h-28 w-full border border-[#d8d1ca] bg-white p-3 text-sm outline-none" placeholder="Descripción comercial del producto"/></label></Field><Field title="Precio y promoción"><div className="grid gap-4 md:grid-cols-3"><Input label="Precio Gs." placeholder="590000"/><Input label="Precio anterior" placeholder="690000"/><Input label="Descuento %" placeholder="15"/></div><label className="mt-4 flex items-center gap-3 text-sm"><input type="checkbox"/> Aplicar descuento automáticamente</label></Field><Field title="Organización"><div className="grid gap-4 md:grid-cols-2"><Select label="Categoría" options={["Moda","Lifestyle","Objetos & Diseño"]}/><Input label="Colección" placeholder="Nueva temporada"/></div></Field><Field title="Variantes e inventario"><div className="grid gap-4 md:grid-cols-3"><Input label="Talles" placeholder="S, M, L, XL"/><Input label="Colores" placeholder="Negro, Beige"/><Input label="Stock" placeholder="10"/></div></Field><Field title="Imágenes"><label className="flex min-h-36 cursor-pointer flex-col items-center justify-center border border-dashed border-[#aaa29a] bg-white text-center"><ImagePlus className="size-6"/><span className="mt-3 text-sm">Subir imágenes del producto</span><span className="mt-1 text-xs text-[#817a74]">Principal + galería</span><input type="file" multiple accept="image/*" className="hidden"/></label></Field><div className="flex justify-end gap-3 border-t border-[#d9d2cb] pt-5"><button type="button" onClick={()=>setOpen(false)} className="border border-[#cfc7c0] px-5 py-3 text-xs">Cancelar</button><button className="bg-[#201e1c] px-6 py-3 text-xs text-white">Guardar producto</button></div></form></div></div>}
  </div>;
}
function Stat({value,label}:{value:string;label:string}){return <div className="border border-[#d9d2cb] bg-[#fbf9f6] p-4"><p className="font-serif text-3xl">{value}</p><p className="mt-1 text-[9px] uppercase tracking-[.16em] text-[#817a74]">{label}</p></div>}
function Step({n,title,copy,children}:{n:string;title:string;copy:string;children?:React.ReactNode}){return <div className="border border-[#d9d2cb] bg-[#fbf9f6] p-5"><span className="text-[9px] tracking-[.2em] text-[#817a74]">{n}</span><h3 className="mt-3 font-serif text-xl">{title}</h3><p className="mt-2 text-xs leading-5 text-[#756f69]">{copy}</p>{children}</div>}
function PackageEmpty(){return <div className="mx-auto flex size-14 items-center justify-center border border-[#d9d2cb] bg-white"><FileSpreadsheet className="size-5"/></div>}
function Span({children}:{children:React.ReactNode}){return <span className="text-[10px] uppercase tracking-[.14em] text-[#706a65]">{children}</span>}
function Input({label,placeholder}:{label:string;placeholder:string}){return <label className="block"><Span>{label}</Span><input placeholder={placeholder} className="mt-2 h-11 w-full border border-[#d8d1ca] bg-white px-3 text-sm outline-none focus:border-[#201e1c]"/></label>}
function Select({label,options}:{label:string;options:string[]}){return <label className="block"><Span>{label}</Span><select className="mt-2 h-11 w-full border border-[#d8d1ca] bg-white px-3 text-sm outline-none">{options.map(x=><option key={x}>{x}</option>)}</select></label>}
function Field({title,children}:{title:string;children:React.ReactNode}){return <section><h3 className="mb-4 border-b border-[#d9d2cb] pb-3 font-serif text-xl">{title}</h3>{children}</section>}
