"use client";

import { useState } from "react";
import { ImagePlus, Plus, Search, X } from "lucide-react";

export default function ProductsPage() {
  const [open,setOpen]=useState(false);
  const [search,setSearch]=useState("");
  return <div className="mx-auto max-w-[1500px]">
    <div className="flex flex-col gap-4 border-b border-[#d6cfc8] pb-6 md:flex-row md:items-end md:justify-between"><div><p className="text-[10px] uppercase tracking-[.2em] text-[#817a74]">Catálogo</p><h1 className="mt-2 font-serif text-4xl">Productos</h1><p className="mt-2 text-sm text-[#756f69]">Creá y administrá productos, variantes, precios, imágenes y stock.</p></div><button onClick={()=>setOpen(true)} className="flex w-fit items-center gap-2 bg-[#201e1c] px-5 py-3 text-[10px] uppercase tracking-[.16em] text-white"><Plus className="size-4"/> Nuevo producto</button></div>
    <div className="mt-6 border border-[#d9d2cb] bg-[#fbf9f6]"><div className="flex flex-col gap-3 border-b border-[#ddd6cf] p-4 md:flex-row"><label className="flex flex-1 items-center gap-3 border border-[#ddd6cf] bg-white px-4"><Search className="size-4 text-[#817a74]"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar por nombre, SKU o marca" className="h-11 w-full bg-transparent text-sm outline-none"/></label><select className="h-11 border border-[#ddd6cf] bg-white px-4 text-sm"><option>Todas las categorías</option><option>Moda</option><option>Lifestyle</option><option>Objetos & Diseño</option></select><select className="h-11 border border-[#ddd6cf] bg-white px-4 text-sm"><option>Todos los estados</option><option>Activo</option><option>Borrador</option><option>Sin stock</option></select></div><div className="p-10 text-center"><PackageEmpty/><h2 className="mt-5 font-serif text-2xl">Tu catálogo empieza acá.</h2><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-[#817a74]">Agregá el primer producto real de RUA y asignale marca, categoría, precio, descuento, talles, colores y stock.</p><button onClick={()=>setOpen(true)} className="mt-6 border-b border-[#201e1c] pb-1 text-[10px] uppercase tracking-[.16em]">Agregar producto →</button></div></div>
    {open&&<div className="fixed inset-0 z-50 flex justify-end bg-black/35"><div className="h-full w-full max-w-2xl overflow-y-auto bg-[#f7f4ef] shadow-2xl"><div className="sticky top-0 z-10 flex items-center justify-between border-b border-[#d9d2cb] bg-[#f7f4ef] px-6 py-5"><div><p className="text-[9px] uppercase tracking-[.2em] text-[#817a74]">Catálogo RUA</p><h2 className="font-serif text-3xl">Nuevo producto</h2></div><button onClick={()=>setOpen(false)}><X/></button></div><form className="space-y-7 p-6" onSubmit={e=>{e.preventDefault();setOpen(false)}}><Field title="Información"><div className="grid gap-4 md:grid-cols-2"><Input label="Nombre del producto" placeholder="Ej. Vestido lino"/><Input label="Marca" placeholder="Ej. Paradiso"/><Input label="SKU" placeholder="RUA-0001"/><Select label="Estado" options={["Activo","Borrador"]}/></div><label className="block"><Span>Descripción</Span><textarea className="mt-2 min-h-28 w-full border border-[#d8d1ca] bg-white p-3 text-sm outline-none" placeholder="Descripción comercial del producto"/></label></Field><Field title="Precio y promoción"><div className="grid gap-4 md:grid-cols-3"><Input label="Precio Gs." placeholder="590000"/><Input label="Precio anterior" placeholder="690000"/><Input label="Descuento %" placeholder="15"/></div><label className="mt-4 flex items-center gap-3 text-sm"><input type="checkbox"/> Aplicar descuento automáticamente</label></Field><Field title="Organización"><div className="grid gap-4 md:grid-cols-2"><Select label="Categoría" options={["Moda","Lifestyle","Objetos & Diseño"]}/><Input label="Colección" placeholder="Nueva temporada"/></div></Field><Field title="Variantes e inventario"><div className="grid gap-4 md:grid-cols-3"><Input label="Talles" placeholder="S, M, L, XL"/><Input label="Colores" placeholder="Negro, Beige"/><Input label="Stock" placeholder="10"/></div></Field><Field title="Imágenes"><label className="flex min-h-36 cursor-pointer flex-col items-center justify-center border border-dashed border-[#aaa29a] bg-white text-center"><ImagePlus className="size-6"/><span className="mt-3 text-sm">Subir imágenes del producto</span><span className="mt-1 text-xs text-[#817a74]">Principal + galería</span><input type="file" multiple accept="image/*" className="hidden"/></label></Field><div className="flex justify-end gap-3 border-t border-[#d9d2cb] pt-5"><button type="button" onClick={()=>setOpen(false)} className="border border-[#cfc7c0] px-5 py-3 text-xs">Cancelar</button><button className="bg-[#201e1c] px-6 py-3 text-xs text-white">Guardar producto</button></div></form></div></div>}
  </div>;
}
function PackageEmpty(){return <div className="mx-auto flex size-14 items-center justify-center border border-[#d9d2cb] bg-white"><Plus className="size-5"/></div>}
function Span({children}:{children:React.ReactNode}){return <span className="text-[10px] uppercase tracking-[.14em] text-[#706a65]">{children}</span>}
function Input({label,placeholder}:{label:string;placeholder:string}){return <label className="block"><Span>{label}</Span><input placeholder={placeholder} className="mt-2 h-11 w-full border border-[#d8d1ca] bg-white px-3 text-sm outline-none focus:border-[#201e1c]"/></label>}
function Select({label,options}:{label:string;options:string[]}){return <label className="block"><Span>{label}</Span><select className="mt-2 h-11 w-full border border-[#d8d1ca] bg-white px-3 text-sm outline-none">{options.map(x=><option key={x}>{x}</option>)}</select></label>}
function Field({title,children}:{title:string;children:React.ReactNode}){return <section><h3 className="mb-4 border-b border-[#d9d2cb] pb-3 font-serif text-xl">{title}</h3>{children}</section>}
