'use client'
import { Suspense, useEffect, useState } from 'react'
import { useSearchParams, useRouter } from 'next/navigation'
import { useCartStore } from '@/store/cartStore'
import { useCheckoutStore } from '@/store/checkoutStore'
import { createClient } from '@/lib/supabase/client'
import Link from 'next/link'
import { Building2, Check, CreditCard, MapPin, Store } from 'lucide-react'

type PaymentMethod='card'|'transfer'|'store'
const money=(v:number)=>`Gs. ${new Intl.NumberFormat('es-PY').format(v)}`

function PaymentContent(){
 const router=useRouter();const params=useSearchParams();const orderId=params.get('orderId');const {items,clearCart}=useCartStore();const {shipping,reset}=useCheckoutStore();const [method,setMethod]=useState<PaymentMethod>('card');const [submitting,setSubmitting]=useState(false);const subtotal=items.reduce((s,i)=>s+(Number(i.product?.offer_price??i.product?.price)||0)*i.quantity,0)
 useEffect(()=>{if(!orderId)router.push('/checkout')},[orderId,router])
 const confirm=async()=>{if(!orderId)return;setSubmitting(true);const supabase=createClient();const {data:{user}}=await supabase.auth.getUser();if(!user){router.push('/login');return}try{await supabase.from('orders').update({payment_method:method,payment_status:'pending'}).eq('id',orderId);await clearCart(user.id);reset();router.push(`/checkout/verify?orderId=${orderId}&status=pending`)}finally{setSubmitting(false)}}
 const options=[{id:'card' as const,icon:CreditCard,title:'Tarjeta de crédito o débito',copy:'La integración de la pasarela se habilitará con el proveedor de pagos de RUA.'},{id:'transfer' as const,icon:Building2,title:'Transferencia bancaria',copy:'Los datos para transferencia se informan al confirmar el pedido.'},{id:'store' as const,icon:Store,title:'Pago coordinado con la tienda',copy:'Reservá el pedido y coordiná el pago con RUA Vera.'}]
 return <main className="min-h-screen bg-[#f7f4ef] px-[4%] py-12 text-[#201e1c]"><div className="mx-auto max-w-[1200px]"><p className="text-[9px] uppercase tracking-[0.2em] text-[#6e6965]">Paso 2 de 2</p><h1 className="mt-2 font-serif text-5xl">Forma de pago</h1><div className="mt-10 grid gap-12 lg:grid-cols-[1fr_380px]"><section><h2 className="font-serif text-2xl">Elegí cómo pagar</h2><div className="mt-5 space-y-3">{options.map(({id,icon:Icon,title,copy})=><button key={id} onClick={()=>setMethod(id)} className={`flex w-full items-start gap-4 border p-5 text-left ${method===id?'border-[#201e1c] bg-white':'border-[#d9d2cb]'}`}><Icon className="mt-1" size={20}/><div className="flex-1"><p className="font-medium">{title}</p><p className="mt-2 text-xs leading-5 text-[#6e6965]">{copy}</p></div>{method===id&&<Check size={17}/>}</button>)}</div><div className="mt-8 flex gap-3"><Link href="/checkout" className="flex-1 border border-[#201e1c] py-4 text-center text-[10px] uppercase tracking-[0.16em]">Volver</Link><button onClick={confirm} disabled={submitting||subtotal<=0} className="flex-1 bg-[#201e1c] py-4 text-[10px] uppercase tracking-[0.16em] text-white disabled:opacity-40">{submitting?'Confirmando...':'Confirmar pedido'}</button></div></section><aside className="h-fit border border-[#d9d2cb] bg-white p-7 lg:sticky lg:top-36"><p className="text-[9px] uppercase tracking-[0.18em] text-[#6e6965]">Entrega</p><div className="mt-4 flex gap-3">{shipping.delivery_method==='pickup'?<Store size={18}/>:<MapPin size={18}/>}<div><p className="font-medium">{shipping.delivery_method==='pickup'?'Retiro en tienda':'Entrega a domicilio'}</p><p className="mt-1 text-xs leading-5 text-[#6e6965]">{shipping.delivery_method==='pickup'?'RUA Vera · Asunción':`${shipping.address}${shipping.city?`, ${shipping.city}`:''}`}</p></div></div><div className="mt-6 border-t border-[#d9d2cb] pt-5"><p className="text-xs text-[#6e6965]">A nombre de</p><p className="mt-1 text-sm">{shipping.full_name}</p><p className="text-xs text-[#6e6965]">{shipping.phone}</p></div><div className="mt-6 flex justify-between border-t border-[#d9d2cb] pt-5"><span>Total productos</span><strong>{money(subtotal)}</strong></div><p className="mt-4 text-xs leading-5 text-[#6e6965]">No se cobra automáticamente hasta que la integración de pago correspondiente esté habilitada.</p></aside></div></div></main>
}
export default function PaymentPage(){return <Suspense fallback={<div className="min-h-screen bg-[#f7f4ef]"/>}><PaymentContent/></Suspense>}
